from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt
from datetime import datetime

import sys
import serial
import serial.tools.list_ports
import threading
import json
import logo

test = 16

class Ui_MainWindow(object):
        time = []
        soc_values = []
        battery_voltage_values = []
        cell_v = [0 for i in range(test)]
        cell_v_label = [0 for i in range(test)]

        ser_ports = serial.tools.list_ports.comports()
        ports = [port.name for port in ser_ports]
        brate = ['50', '75', '110', '134', '150', '200', '300', '600', '1200', '1800', '2400', '4800', '9600', '19200', '38400', '57600', '115200']

        config = {
                'port': ports,
                'baud_rate': brate
        }
        
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1700, 900)
                #MainWindow.showMaximized()
                MainWindow.setMinimumSize(QtCore.QSize(1500, 1000))
                MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
                MainWindow.setPalette(palette)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                MainWindow.setFont(font)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
                self.centralwidget.setObjectName("centralwidget")
                self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
                self.gridLayout_6.setObjectName("gridLayout_6")
                self.top_navbar = QtWidgets.QHBoxLayout()
                self.top_navbar.setObjectName("top_navbar")
                self.label = QtWidgets.QLabel(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
                self.label.setSizePolicy(sizePolicy)
                self.label.setMinimumSize(QtCore.QSize(150, 40))
                self.label.setBaseSize(QtCore.QSize(150, 40))
                self.label.setStyleSheet("image: url(:/logo/1.png);")
                self.label.setText("")
                self.label.setScaledContents(True)
                self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label.setObjectName("label")
                self.top_navbar.addWidget(self.label)
                spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
                self.top_navbar.addItem(spacerItem)
                self.config_port = QtWidgets.QComboBox(self.centralwidget)
                self.config_port.setObjectName("config_port")
                self.top_navbar.addWidget(self.config_port)
                spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
                self.top_navbar.addItem(spacerItem1)
                self.config_brate = QtWidgets.QComboBox(self.centralwidget)
                self.config_brate.setObjectName("config_brate")
                self.top_navbar.addWidget(self.config_brate)
                spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
                self.top_navbar.addItem(spacerItem2)
                self.time_sync = QtWidgets.QPushButton(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(10)
                sizePolicy.setVerticalStretch(10)
                sizePolicy.setHeightForWidth(self.time_sync.sizePolicy().hasHeightForWidth())
                self.time_sync.setSizePolicy(sizePolicy)
                self.time_sync.setMinimumSize(QtCore.QSize(10, 10))
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                self.time_sync.setFont(font)
                self.time_sync.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                "border-radius: 15px;\n"
                "padding: 10px;")
                self.time_sync.setObjectName("time_sync")
                self.top_navbar.addWidget(self.time_sync)
                self.gridLayout_6.addLayout(self.top_navbar, 0, 0, 1, 4)
                self.line_4 = QtWidgets.QFrame(self.centralwidget)
                self.line_4.setStyleSheet("color: rgb(127, 127, 127);")
                self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
                self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
                self.line_4.setObjectName("line_4")
                self.gridLayout_6.addWidget(self.line_4, 1, 0, 1, 4)
                self.battery_stats_frame = QtWidgets.QFrame(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.battery_stats_frame.sizePolicy().hasHeightForWidth())
                self.battery_stats_frame.setSizePolicy(sizePolicy)
                self.battery_stats_frame.setMinimumSize(QtCore.QSize(250, 750))
                self.battery_stats_frame.setMaximumSize(QtCore.QSize(300, 16777215))
                self.battery_stats_frame.setStyleSheet("background-color: rgb(30, 30, 30);\n"
                "border-radius:10px;\n"
                "font:  \"Montserrat\";")
                self.battery_stats_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.battery_stats_frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.battery_stats_frame.setObjectName("battery_stats_frame")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.battery_stats_frame)
                self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
                self.verticalLayout_2.setSpacing(5)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.battery_stats = QtWidgets.QVBoxLayout()
                self.battery_stats.setContentsMargins(5, 5, 5, 5)
                self.battery_stats.setSpacing(5)
                self.battery_stats.setObjectName("battery_stats")
                self.battery_stats_label = QtWidgets.QLabel(self.battery_stats_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.battery_stats_label.sizePolicy().hasHeightForWidth())
                self.battery_stats_label.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(12)
                font.setBold(False)
                font.setWeight(50)
                self.battery_stats_label.setFont(font)
                self.battery_stats_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 12pt \"Montserrat\";")
                self.battery_stats_label.setTextFormat(QtCore.Qt.AutoText)
                self.battery_stats_label.setObjectName("battery_stats_label")
                self.battery_stats.addWidget(self.battery_stats_label)
                self.gridLayout = QtWidgets.QGridLayout()
                self.gridLayout.setObjectName("gridLayout")
                self.total_current_label = QtWidgets.QLabel(self.battery_stats_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.total_current_label.setFont(font)
                self.total_current_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.total_current_label.setObjectName("total_current_label")
                self.gridLayout.addWidget(self.total_current_label, 1, 0, 1, 1)
                self.soc_label = QtWidgets.QLabel(self.battery_stats_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.soc_label.setFont(font)
                self.soc_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.soc_label.setObjectName("soc_label")
                self.gridLayout.addWidget(self.soc_label, 2, 0, 1, 1)
                self.status = QtWidgets.QLabel(self.battery_stats_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.status.setFont(font)
                self.status.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.status.setObjectName("status")
                self.gridLayout.addWidget(self.status, 3, 1, 1, 1)
                self.soc = QtWidgets.QLabel(self.battery_stats_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.soc.setFont(font)
                self.soc.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.soc.setObjectName("soc")
                self.gridLayout.addWidget(self.soc, 2, 1, 1, 1)
                self.voltage = QtWidgets.QLabel(self.battery_stats_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.voltage.setFont(font)
                self.voltage.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.voltage.setObjectName("voltage")
                self.gridLayout.addWidget(self.voltage, 0, 1, 1, 1)
                self.voltage_label = QtWidgets.QLabel(self.battery_stats_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.voltage_label.setFont(font)
                self.voltage_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.voltage_label.setObjectName("voltage_label")
                self.gridLayout.addWidget(self.voltage_label, 0, 0, 1, 1)
                self.total_current = QtWidgets.QLabel(self.battery_stats_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.total_current.setFont(font)
                self.total_current.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.total_current.setObjectName("total_current")
                self.gridLayout.addWidget(self.total_current, 1, 1, 1, 1)
                self.status_label = QtWidgets.QLabel(self.battery_stats_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.status_label.setFont(font)
                self.status_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.status_label.setObjectName("status_label")
                self.gridLayout.addWidget(self.status_label, 3, 0, 1, 1)
                self.battery_stats.addLayout(self.gridLayout)
                self.mosfet_status_label = QtWidgets.QLabel(self.battery_stats_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.mosfet_status_label.sizePolicy().hasHeightForWidth())
                self.mosfet_status_label.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(12)
                font.setBold(False)
                font.setWeight(50)
                self.mosfet_status_label.setFont(font)
                self.mosfet_status_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 12pt \"Montserrat\";")
                self.mosfet_status_label.setTextFormat(QtCore.Qt.AutoText)
                self.mosfet_status_label.setObjectName("mosfet_status_label")
                self.battery_stats.addWidget(self.mosfet_status_label)
                self.gridLayout_2 = QtWidgets.QGridLayout()
                self.gridLayout_2.setObjectName("gridLayout_2")
                self.charging_label = QtWidgets.QLabel(self.battery_stats_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.charging_label.setFont(font)
                self.charging_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.charging_label.setObjectName("charging_label")
                self.gridLayout_2.addWidget(self.charging_label, 0, 0, 1, 1)
                self.charging = QtWidgets.QLabel(self.battery_stats_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                self.charging.setFont(font)
                self.charging.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.charging.setObjectName("charging")
                self.gridLayout_2.addWidget(self.charging, 0, 1, 1, 1)
                self.discharging_label = QtWidgets.QLabel(self.battery_stats_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.discharging_label.setFont(font)
                self.discharging_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.discharging_label.setObjectName("discharging_label")
                self.gridLayout_2.addWidget(self.discharging_label, 1, 0, 1, 1)
                self.discharging = QtWidgets.QLabel(self.battery_stats_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                self.discharging.setFont(font)
                self.discharging.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.discharging.setObjectName("discharging")
                self.gridLayout_2.addWidget(self.discharging, 1, 1, 1, 1)
                self.battery_stats.addLayout(self.gridLayout_2)
                self.verticalLayout_2.addLayout(self.battery_stats)
                self.gridLayout_6.addWidget(self.battery_stats_frame, 2, 0, 3, 1)
                self.temp_frame = QtWidgets.QFrame(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.temp_frame.sizePolicy().hasHeightForWidth())
                self.temp_frame.setSizePolicy(sizePolicy)
                self.temp_frame.setMinimumSize(QtCore.QSize(250, 250))
                self.temp_frame.setMaximumSize(QtCore.QSize(300, 16777215))
                self.temp_frame.setStyleSheet("background-color: rgb(207, 207, 207);\n"
                "border-radius:10px;\n"
                "font:  \"Montserrat\";")
                self.temp_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.temp_frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.temp_frame.setObjectName("temp_frame")
                self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.temp_frame)
                self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
                self.verticalLayout_6.setSpacing(5)
                self.verticalLayout_6.setObjectName("verticalLayout_6")
                self.verticalLayout = QtWidgets.QVBoxLayout()
                self.verticalLayout.setObjectName("verticalLayout")
                self.battery_stats_label_6 = QtWidgets.QLabel(self.temp_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.battery_stats_label_6.sizePolicy().hasHeightForWidth())
                self.battery_stats_label_6.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(12)
                font.setBold(False)
                font.setWeight(50)
                self.battery_stats_label_6.setFont(font)
                self.battery_stats_label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
                "font: 12pt \"Montserrat\";")
                self.battery_stats_label_6.setTextFormat(QtCore.Qt.AutoText)
                self.battery_stats_label_6.setObjectName("battery_stats_label_6")
                self.verticalLayout.addWidget(self.battery_stats_label_6, 0, QtCore.Qt.AlignHCenter)
                self.temp_layout = QtWidgets.QGridLayout()
                self.temp_layout.setObjectName("temp_layout")
                self.mosfet_temp_layout = QtWidgets.QGridLayout()
                self.mosfet_temp_layout.setObjectName("mosfet_temp_layout")
                self.mosfet_temp_label = QtWidgets.QLabel(self.temp_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.mosfet_temp_label.setFont(font)
                self.mosfet_temp_label.setStyleSheet("color: rgb(50, 50, 50);\n"
                "font: 9pt \"Montserrat\";")
                self.mosfet_temp_label.setObjectName("mosfet_temp_label")
                self.mosfet_temp_layout.addWidget(self.mosfet_temp_label, 0, 0, 1, 1)
                self.mosfet_temp = QtWidgets.QLabel(self.temp_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.mosfet_temp.setFont(font)
                self.mosfet_temp.setStyleSheet("color: rgb(0,0,0);\n"
                "font: 9pt \"Montserrat\";")
                self.mosfet_temp.setObjectName("mosfet_temp")
                self.mosfet_temp_layout.addWidget(self.mosfet_temp, 0, 1, 1, 1)
                self.temp_layout.addLayout(self.mosfet_temp_layout, 4, 0, 1, 1)
                self.sensor_2_layout = QtWidgets.QGridLayout()
                self.sensor_2_layout.setObjectName("sensor_2_layout")
                self.sensor_2_label = QtWidgets.QLabel(self.temp_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.sensor_2_label.setFont(font)
                self.sensor_2_label.setStyleSheet("color: rgb(50, 50, 50);\n"
                "font: 9pt \"Montserrat\";")
                self.sensor_2_label.setObjectName("sensor_2_label")
                self.sensor_2_layout.addWidget(self.sensor_2_label, 0, 0, 1, 1)
                self.sensor_2 = QtWidgets.QLabel(self.temp_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.sensor_2.setFont(font)
                self.sensor_2.setStyleSheet("color: rgb(0,0,0);\n"
                "font: 9pt \"Montserrat\";")
                self.sensor_2.setObjectName("sensor_2")
                self.sensor_2_layout.addWidget(self.sensor_2, 0, 1, 1, 1)
                self.temp_layout.addLayout(self.sensor_2_layout, 1, 0, 1, 1)
                self.sensor_3_layout = QtWidgets.QGridLayout()
                self.sensor_3_layout.setObjectName("sensor_3_layout")
                self.sensor_3_label = QtWidgets.QLabel(self.temp_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.sensor_3_label.setFont(font)
                self.sensor_3_label.setStyleSheet("color: rgb(50, 50, 50);\n"
                "font: 9pt \"Montserrat\";")
                self.sensor_3_label.setObjectName("sensor_3_label")
                self.sensor_3_layout.addWidget(self.sensor_3_label, 0, 0, 1, 1)
                self.sensor_3 = QtWidgets.QLabel(self.temp_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.sensor_3.setFont(font)
                self.sensor_3.setStyleSheet("color: rgb(0,0,0);\n"
                "font: 9pt \"Montserrat\";")
                self.sensor_3.setObjectName("sensor_3")
                self.sensor_3_layout.addWidget(self.sensor_3, 0, 1, 1, 1)
                self.temp_layout.addLayout(self.sensor_3_layout, 2, 0, 1, 1)
                self.sensor_1_layout = QtWidgets.QGridLayout()
                self.sensor_1_layout.setObjectName("sensor_1_layout")
                self.sensor_1_label = QtWidgets.QLabel(self.temp_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.sensor_1_label.setFont(font)
                self.sensor_1_label.setStyleSheet("color: rgb(50, 50, 50);\n"
                "font: 9pt \"Montserrat\";")
                self.sensor_1_label.setObjectName("sensor_1_label")
                self.sensor_1_layout.addWidget(self.sensor_1_label, 0, 0, 1, 1)
                self.sensor_1 = QtWidgets.QLabel(self.temp_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.sensor_1.setFont(font)
                self.sensor_1.setStyleSheet("color: rgb(0,0,0);\n"
                "font: 9pt \"Montserrat\";")
                self.sensor_1.setObjectName("sensor_1")
                self.sensor_1_layout.addWidget(self.sensor_1, 0, 1, 1, 1)
                self.temp_layout.addLayout(self.sensor_1_layout, 0, 0, 1, 1)
                self.sensor_4_layout = QtWidgets.QGridLayout()
                self.sensor_4_layout.setObjectName("sensor_4_layout")
                self.sensor_4_label = QtWidgets.QLabel(self.temp_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.sensor_4_label.setFont(font)
                self.sensor_4_label.setStyleSheet("color: rgb(50, 50, 50);\n"
                "font: 9pt \"Montserrat\";")
                self.sensor_4_label.setObjectName("sensor_4_label")
                self.sensor_4_layout.addWidget(self.sensor_4_label, 0, 0, 1, 1)
                self.sensor_4 = QtWidgets.QLabel(self.temp_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.sensor_4.setFont(font)
                self.sensor_4.setStyleSheet("color: rgb(0,0,0);\n"
                "font: 9pt \"Montserrat\";")
                self.sensor_4.setObjectName("sensor_4")
                self.sensor_4_layout.addWidget(self.sensor_4, 0, 1, 1, 1)
                self.temp_layout.addLayout(self.sensor_4_layout, 3, 0, 1, 1)
                self.verticalLayout.addLayout(self.temp_layout)
                self.verticalLayout_6.addLayout(self.verticalLayout)
                self.gridLayout_6.addWidget(self.temp_frame, 2, 1, 1, 1)
                self.cell_chemistry_frame = QtWidgets.QFrame(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.cell_chemistry_frame.sizePolicy().hasHeightForWidth())
                self.cell_chemistry_frame.setSizePolicy(sizePolicy)
                self.cell_chemistry_frame.setMinimumSize(QtCore.QSize(700, 250))
                self.cell_chemistry_frame.setStyleSheet("background-color: rgb(207, 207, 207);\n"
                "border-radius:10px;\n"
                "font:  \"Montserrat\";")
                self.cell_chemistry_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.cell_chemistry_frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.cell_chemistry_frame.setObjectName("cell_chemistry_frame")
                self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.cell_chemistry_frame)
                self.verticalLayout_5.setObjectName("verticalLayout_5")
                self.gridLayout_5 = QtWidgets.QGridLayout()
                self.gridLayout_5.setObjectName("gridLayout_5")
                self.chemistry_label = QtWidgets.QLabel(self.cell_chemistry_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.chemistry_label.setFont(font)
                self.chemistry_label.setStyleSheet("color: rgb(50, 50, 50);\n"
                "font: 9pt \"Montserrat\";")
                self.chemistry_label.setObjectName("chemistry_label")
                self.gridLayout_5.addWidget(self.chemistry_label, 0, 0, 1, 1)
                self.chemistry = QtWidgets.QLabel(self.cell_chemistry_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.chemistry.setFont(font)
                self.chemistry.setStyleSheet("color: rgb(0,0,0);\n"
                "font: 9pt \"Montserrat\";")
                self.chemistry.setObjectName("chemistry")
                self.gridLayout_5.addWidget(self.chemistry, 0, 1, 1, 1)
                self.cells_label = QtWidgets.QLabel(self.cell_chemistry_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.cells_label.setFont(font)
                self.cells_label.setStyleSheet("color: rgb(50, 50, 50);\n"
                "font: 9pt \"Montserrat\";")
                self.cells_label.setObjectName("cells_label")
                self.gridLayout_5.addWidget(self.cells_label, 1, 0, 1, 1)
                self.cells = QtWidgets.QLabel(self.cell_chemistry_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.cells.setFont(font)
                self.cells.setStyleSheet("color: rgb(0,0,0);\n"
                "font: 9pt \"Montserrat\";")
                self.cells.setObjectName("cells")
                self.gridLayout_5.addWidget(self.cells, 1, 1, 1, 1)
                self.design_capacity_label = QtWidgets.QLabel(self.cell_chemistry_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.design_capacity_label.setFont(font)
                self.design_capacity_label.setStyleSheet("color: rgb(50, 50, 50);\n"
                "font: 9pt \"Montserrat\";")
                self.design_capacity_label.setObjectName("design_capacity_label")
                self.gridLayout_5.addWidget(self.design_capacity_label, 2, 0, 1, 1)
                self.design_capacity = QtWidgets.QLabel(self.cell_chemistry_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.design_capacity.setFont(font)
                self.design_capacity.setStyleSheet("color: rgb(0,0,0);\n"
                "font: 9pt \"Montserrat\";")
                self.design_capacity.setObjectName("design_capacity")
                self.gridLayout_5.addWidget(self.design_capacity, 2, 1, 1, 1)
                self.battery_min_v_label = QtWidgets.QLabel(self.cell_chemistry_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.battery_min_v_label.setFont(font)
                self.battery_min_v_label.setStyleSheet("color: rgb(50, 50, 50);\n"
                "font: 9pt \"Montserrat\";")
                self.battery_min_v_label.setObjectName("battery_min_v_label")
                self.gridLayout_5.addWidget(self.battery_min_v_label, 3, 0, 1, 1)
                self.battery_min_v = QtWidgets.QLabel(self.cell_chemistry_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.battery_min_v.setFont(font)
                self.battery_min_v.setStyleSheet("color: rgb(0,0,0);\n"
                "font: 9pt \"Montserrat\";")
                self.battery_min_v.setObjectName("battery_min_v")
                self.gridLayout_5.addWidget(self.battery_min_v, 3, 1, 1, 1)
                self.nominal_v_label = QtWidgets.QLabel(self.cell_chemistry_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.nominal_v_label.setFont(font)
                self.nominal_v_label.setStyleSheet("color: rgb(50, 50, 50);\n"
                "font: 9pt \"Montserrat\";")
                self.nominal_v_label.setObjectName("nominal_v_label")
                self.gridLayout_5.addWidget(self.nominal_v_label, 4, 0, 1, 1)
                self.nominal_v = QtWidgets.QLabel(self.cell_chemistry_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.nominal_v.setFont(font)
                self.nominal_v.setStyleSheet("color: rgb(0,0,0);\n"
                "font: 9pt \"Montserrat\";")
                self.nominal_v.setObjectName("nominal_v")
                self.gridLayout_5.addWidget(self.nominal_v, 4, 1, 1, 1)
                self.battery_max_v_label = QtWidgets.QLabel(self.cell_chemistry_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.battery_max_v_label.setFont(font)
                self.battery_max_v_label.setStyleSheet("color: rgb(50, 50, 50);\n"
                "font: 9pt \"Montserrat\";")
                self.battery_max_v_label.setObjectName("battery_max_v_label")
                self.gridLayout_5.addWidget(self.battery_max_v_label, 5, 0, 1, 1)
                self.battery_max_v = QtWidgets.QLabel(self.cell_chemistry_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.battery_max_v.setFont(font)
                self.battery_max_v.setStyleSheet("color: rgb(0,0,0);\n"
                "font: 9pt \"Montserrat\";")
                self.battery_max_v.setObjectName("battery_max_v")
                self.gridLayout_5.addWidget(self.battery_max_v, 5, 1, 1, 1)
                self.verticalLayout_5.addLayout(self.gridLayout_5)
                self.gridLayout_6.addWidget(self.cell_chemistry_frame, 2, 2, 1, 1)
                self.cell_stats_label = QtWidgets.QFrame(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.cell_stats_label.sizePolicy().hasHeightForWidth())
                self.cell_stats_label.setSizePolicy(sizePolicy)
                self.cell_stats_label.setMinimumSize(QtCore.QSize(250, 250))
                self.cell_stats_label.setMaximumSize(QtCore.QSize(300, 16777215))
                self.cell_stats_label.setStyleSheet("background-color: rgb(30, 30, 30);\n"
                "border-radius:10px;\n"
                "font:  \"Montserrat\";")
                self.cell_stats_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.cell_stats_label.setFrameShadow(QtWidgets.QFrame.Raised)
                self.cell_stats_label.setObjectName("cell_stats_label")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cell_stats_label)
                self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
                self.verticalLayout_3.setSpacing(5)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.verticalLayout_4 = QtWidgets.QVBoxLayout()
                self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
                self.verticalLayout_4.setSpacing(5)
                self.verticalLayout_4.setObjectName("verticalLayout_4")
                self.battery_stats_label_2 = QtWidgets.QLabel(self.cell_stats_label)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.battery_stats_label_2.sizePolicy().hasHeightForWidth())
                self.battery_stats_label_2.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(12)
                font.setBold(False)
                font.setWeight(50)
                self.battery_stats_label_2.setFont(font)
                self.battery_stats_label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 12pt \"Montserrat\";")
                self.battery_stats_label_2.setTextFormat(QtCore.Qt.AutoText)
                self.battery_stats_label_2.setObjectName("battery_stats_label_2")
                self.verticalLayout_4.addWidget(self.battery_stats_label_2, 0, QtCore.Qt.AlignHCenter)
                self.gridLayout_3 = QtWidgets.QGridLayout()
                self.gridLayout_3.setObjectName("gridLayout_3")
                self.max_v_label = QtWidgets.QLabel(self.cell_stats_label)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.max_v_label.setFont(font)
                self.max_v_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.max_v_label.setObjectName("max_v_label")
                self.gridLayout_3.addWidget(self.max_v_label, 0, 0, 1, 1)
                self.max_v = QtWidgets.QLabel(self.cell_stats_label)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.max_v.setFont(font)
                self.max_v.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.max_v.setObjectName("max_v")
                self.gridLayout_3.addWidget(self.max_v, 0, 1, 1, 1)
                self.min_v_label = QtWidgets.QLabel(self.cell_stats_label)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.min_v_label.setFont(font)
                self.min_v_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.min_v_label.setObjectName("min_v_label")
                self.gridLayout_3.addWidget(self.min_v_label, 1, 0, 1, 1)
                self.min_v = QtWidgets.QLabel(self.cell_stats_label)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.min_v.setFont(font)
                self.min_v.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.min_v.setObjectName("min_v")
                self.gridLayout_3.addWidget(self.min_v, 1, 1, 1, 1)
                self.avg_cell_v_label = QtWidgets.QLabel(self.cell_stats_label)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.avg_cell_v_label.setFont(font)
                self.avg_cell_v_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.avg_cell_v_label.setObjectName("avg_cell_v_label")
                self.gridLayout_3.addWidget(self.avg_cell_v_label, 2, 0, 1, 1)
                self.avg_cell_v = QtWidgets.QLabel(self.cell_stats_label)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.avg_cell_v.setFont(font)
                self.avg_cell_v.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.avg_cell_v.setObjectName("avg_cell_v")
                self.gridLayout_3.addWidget(self.avg_cell_v, 2, 1, 1, 1)
                self.difference_label = QtWidgets.QLabel(self.cell_stats_label)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.difference_label.setFont(font)
                self.difference_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.difference_label.setObjectName("difference_label")
                self.gridLayout_3.addWidget(self.difference_label, 3, 0, 1, 1)
                self.difference = QtWidgets.QLabel(self.cell_stats_label)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.difference.setFont(font)
                self.difference.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.difference.setObjectName("difference")
                self.gridLayout_3.addWidget(self.difference, 3, 1, 1, 1)
                self.verticalLayout_4.addLayout(self.gridLayout_3)
                self.verticalLayout_3.addLayout(self.verticalLayout_4)
                self.gridLayout_6.addWidget(self.cell_stats_label, 2, 3, 1, 1)
                self.cell_voltage_frame = QtWidgets.QFrame(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.cell_voltage_frame.sizePolicy().hasHeightForWidth())
                self.cell_voltage_frame.setSizePolicy(sizePolicy)
                self.cell_voltage_frame.setMinimumSize(QtCore.QSize(250, 500))
                self.cell_voltage_frame.setMaximumSize(QtCore.QSize(300, 16777215))
                self.cell_voltage_frame.setStyleSheet("background-color: rgb(207, 207, 207);\n"
                "border-radius:10px;\n"
                "font:  \"Montserrat\";")
                self.cell_voltage_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.cell_voltage_frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.cell_voltage_frame.setObjectName("cell_voltage_frame")
                self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.cell_voltage_frame)
                self.verticalLayout_8.setObjectName("verticalLayout_8")
                self.verticalLayout_7 = QtWidgets.QVBoxLayout()
                self.verticalLayout_7.setObjectName("verticalLayout_7")
                self.battery_stats_label_8 = QtWidgets.QLabel(self.cell_voltage_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.battery_stats_label_8.sizePolicy().hasHeightForWidth())
                self.battery_stats_label_8.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(12)
                font.setBold(False)
                font.setWeight(50)
                self.battery_stats_label_8.setFont(font)
                self.battery_stats_label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
                "font: 12pt \"Montserrat\";")
                self.battery_stats_label_8.setTextFormat(QtCore.Qt.AutoText)
                self.battery_stats_label_8.setObjectName("battery_stats_label_8")
                self.verticalLayout_7.addWidget(self.battery_stats_label_8, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
                self.scrollArea = QtWidgets.QScrollArea(self.cell_voltage_frame)
                self.scrollArea.setWidgetResizable(True)
                self.scrollArea.setObjectName("scrollArea")
                self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
                self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 229, 442))
                self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.gridLayout_4 = QtWidgets.QGridLayout()
                self.gridLayout_4.setObjectName("gridLayout_4")
                
                for i in range(test):
                        self.cell_v_label[i] = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
                        font = QtGui.QFont()
                        font.setFamily("Montserrat")
                        font.setPointSize(9)
                        font.setBold(False)
                        font.setItalic(False)
                        font.setWeight(50)
                        self.cell_v_label[i].setFont(font)
                        self.cell_v_label[i].setStyleSheet("color: rgb(50, 50, 50);\n"
                        "font: 9pt \"Montserrat\";")
                        self.cell_v_label[i].setObjectName(f"cell_v_label_{i+1}")
                        self.gridLayout_4.addWidget(self.cell_v_label[i], i, 0, 1, 1)

                        self.cell_v[i] = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
                        font = QtGui.QFont()
                        font.setFamily("Montserrat")
                        font.setPointSize(9)
                        font.setBold(False)
                        font.setItalic(False)
                        font.setWeight(50)
                        self.cell_v[i].setFont(font)
                        self.cell_v[i].setStyleSheet("color: rgb(0,0,0);\n"
                        "font: 9pt \"Montserrat\";")
                        self.cell_v[i].setObjectName(f"cell_v_{i+1}")
                        self.gridLayout_4.addWidget(self.cell_v[i], i, 1, 1, 1)
                        
                self.horizontalLayout.addLayout(self.gridLayout_4)
                self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
                self.verticalLayout_7.addWidget(self.scrollArea)
                self.verticalLayout_8.addLayout(self.verticalLayout_7)
                self.gridLayout_6.addWidget(self.cell_voltage_frame, 3, 1, 2, 1)
                self.empty_layout_1 = QtWidgets.QVBoxLayout()
                self.empty_layout_1.setObjectName("empty_layout_1")
                self.gridLayout_6.addLayout(self.empty_layout_1, 3, 2, 1, 1)
                self.alarm_frame = QtWidgets.QFrame(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.alarm_frame.sizePolicy().hasHeightForWidth())
                self.alarm_frame.setSizePolicy(sizePolicy)
                self.alarm_frame.setMinimumSize(QtCore.QSize(250, 500))
                self.alarm_frame.setMaximumSize(QtCore.QSize(300, 16777215))
                self.alarm_frame.setStyleSheet("background-color: rgb(30, 30, 30);\n"
                "border-radius:10px;\n"
                "font:  \"Montserrat\";")
                self.alarm_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.alarm_frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.alarm_frame.setObjectName("alarm_frame")
                self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.alarm_frame)
                self.verticalLayout_15.setContentsMargins(5, 5, 5, 5)
                self.verticalLayout_15.setSpacing(5)
                self.verticalLayout_15.setObjectName("verticalLayout_15")
                self.verticalLayout_16 = QtWidgets.QVBoxLayout()
                self.verticalLayout_16.setContentsMargins(5, 5, 5, 5)
                self.verticalLayout_16.setSpacing(5)
                self.verticalLayout_16.setObjectName("verticalLayout_16")
                self.alarm_label = QtWidgets.QLabel(self.alarm_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.alarm_label.sizePolicy().hasHeightForWidth())
                self.alarm_label.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(12)
                font.setBold(False)
                font.setWeight(50)
                self.alarm_label.setFont(font)
                self.alarm_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 12pt \"Montserrat\";")
                self.alarm_label.setTextFormat(QtCore.Qt.AutoText)
                self.alarm_label.setObjectName("alarm_label")
                self.verticalLayout_16.addWidget(self.alarm_label, 0, QtCore.Qt.AlignHCenter)
                self.alarm_layout = QtWidgets.QGridLayout()
                self.alarm_layout.setObjectName("alarm_layout")
                self.ssc_button = QtWidgets.QRadioButton(self.alarm_frame)
                self.ssc_button.setText("")
                self.ssc_button.setObjectName("ssc_button")
                self.alarm_layout.addWidget(self.ssc_button, 3, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
                self.ssc_label = QtWidgets.QLabel(self.alarm_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.ssc_label.setFont(font)
                self.ssc_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.ssc_label.setObjectName("ssc_label")
                self.alarm_layout.addWidget(self.ssc_label, 3, 2, 1, 1)
                self.over_temp_label = QtWidgets.QLabel(self.alarm_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.over_temp_label.setFont(font)
                self.over_temp_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.over_temp_label.setObjectName("over_temp_label")
                self.alarm_layout.addWidget(self.over_temp_label, 2, 2, 1, 1)
                self.over_v_label = QtWidgets.QLabel(self.alarm_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.over_v_label.setFont(font)
                self.over_v_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.over_v_label.setObjectName("over_v_label")
                self.alarm_layout.addWidget(self.over_v_label, 0, 2, 1, 1)
                self.under_v_label = QtWidgets.QLabel(self.alarm_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.under_v_label.setFont(font)
                self.under_v_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.under_v_label.setObjectName("under_v_label")
                self.alarm_layout.addWidget(self.under_v_label, 1, 2, 1, 1)
                self.under_v_button = QtWidgets.QRadioButton(self.alarm_frame)
                self.under_v_button.setText("")
                self.under_v_button.setObjectName("under_v_button")
                self.alarm_layout.addWidget(self.under_v_button, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
                self.over_v_button = QtWidgets.QRadioButton(self.alarm_frame)
                self.over_v_button.setText("")
                self.over_v_button.setObjectName("over_v_button")
                self.alarm_layout.addWidget(self.over_v_button, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
                self.over_temp_button = QtWidgets.QRadioButton(self.alarm_frame)
                self.over_temp_button.setText("")
                self.over_temp_button.setObjectName("over_temp_button")
                self.alarm_layout.addWidget(self.over_temp_button, 2, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
                self.over_c_button = QtWidgets.QRadioButton(self.alarm_frame)
                self.over_c_button.setText("")
                self.over_c_button.setObjectName("over_c_button")
                self.alarm_layout.addWidget(self.over_c_button, 4, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
                self.over_c_label = QtWidgets.QLabel(self.alarm_frame)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.over_c_label.setFont(font)
                self.over_c_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 9pt \"Montserrat\";")
                self.over_c_label.setObjectName("over_c_label")
                self.alarm_layout.addWidget(self.over_c_label, 4, 2, 1, 1)
                self.verticalLayout_16.addLayout(self.alarm_layout)
                self.verticalLayout_15.addLayout(self.verticalLayout_16)
                self.gridLayout_6.addWidget(self.alarm_frame, 3, 3, 2, 1)
                self.empty_layout_2 = QtWidgets.QVBoxLayout()
                self.empty_layout_2.setObjectName("empty_layout_2")
                self.gridLayout_6.addLayout(self.empty_layout_2, 4, 2, 1, 1)
                self.bottom_line = QtWidgets.QFrame(self.centralwidget)
                self.bottom_line.setStyleSheet("color: rgb(127, 127, 127);")
                self.bottom_line.setFrameShadow(QtWidgets.QFrame.Plain)
                self.bottom_line.setFrameShape(QtWidgets.QFrame.HLine)
                self.bottom_line.setObjectName("bottom_line")
                self.gridLayout_6.addWidget(self.bottom_line, 5, 0, 1, 4)
                self.bottom_statusbar = QtWidgets.QHBoxLayout()
                self.bottom_statusbar.setContentsMargins(5, 5, 5, 5)
                self.bottom_statusbar.setSpacing(5)
                self.bottom_statusbar.setObjectName("bottom_statusbar")
                spacerItem3 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
                self.bottom_statusbar.addItem(spacerItem3)
                self.gui_v_label = QtWidgets.QLabel(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.gui_v_label.sizePolicy().hasHeightForWidth())
                self.gui_v_label.setSizePolicy(sizePolicy)
                self.gui_v_label.setMinimumSize(QtCore.QSize(0, 0))
                self.gui_v_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setWeight(50)
                self.gui_v_label.setFont(font)
                self.gui_v_label.setStyleSheet("color: rgb(74, 74, 74);")
                self.gui_v_label.setObjectName("gui_v_label")
                self.bottom_statusbar.addWidget(self.gui_v_label)
                self.gui_v = QtWidgets.QLabel(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.gui_v.sizePolicy().hasHeightForWidth())
                self.gui_v.setSizePolicy(sizePolicy)
                self.gui_v.setMinimumSize(QtCore.QSize(0, 0))
                self.gui_v.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setWeight(50)
                self.gui_v.setFont(font)
                self.gui_v.setObjectName("gui_v")
                self.bottom_statusbar.addWidget(self.gui_v)
                spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
                self.bottom_statusbar.addItem(spacerItem4)
                self.hardware_v_label = QtWidgets.QLabel(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.hardware_v_label.sizePolicy().hasHeightForWidth())
                self.hardware_v_label.setSizePolicy(sizePolicy)
                self.hardware_v_label.setMinimumSize(QtCore.QSize(0, 0))
                self.hardware_v_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setWeight(50)
                self.hardware_v_label.setFont(font)
                self.hardware_v_label.setStyleSheet("color: rgb(74, 74, 74);")
                self.hardware_v_label.setObjectName("hardware_v_label")
                self.bottom_statusbar.addWidget(self.hardware_v_label)
                self.hardware_v = QtWidgets.QLabel(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.hardware_v.sizePolicy().hasHeightForWidth())
                self.hardware_v.setSizePolicy(sizePolicy)
                self.hardware_v.setMinimumSize(QtCore.QSize(0, 0))
                self.hardware_v.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setWeight(50)
                self.hardware_v.setFont(font)
                self.hardware_v.setObjectName("hardware_v")
                self.bottom_statusbar.addWidget(self.hardware_v)
                spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
                self.bottom_statusbar.addItem(spacerItem5)
                self.firmware_v_label = QtWidgets.QLabel(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.firmware_v_label.sizePolicy().hasHeightForWidth())
                self.firmware_v_label.setSizePolicy(sizePolicy)
                self.firmware_v_label.setMinimumSize(QtCore.QSize(0, 0))
                self.firmware_v_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setWeight(50)
                self.firmware_v_label.setFont(font)
                self.firmware_v_label.setStyleSheet("color: rgb(74, 74, 74);")
                self.firmware_v_label.setObjectName("firmware_v_label")
                self.bottom_statusbar.addWidget(self.firmware_v_label)
                self.firmware_v = QtWidgets.QLabel(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.firmware_v.sizePolicy().hasHeightForWidth())
                self.firmware_v.setSizePolicy(sizePolicy)
                self.firmware_v.setMinimumSize(QtCore.QSize(0, 0))
                self.firmware_v.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setWeight(50)
                self.firmware_v.setFont(font)
                self.firmware_v.setObjectName("firmware_v")
                self.bottom_statusbar.addWidget(self.firmware_v)
                spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
                self.bottom_statusbar.addItem(spacerItem6)
                self.bms_v_label = QtWidgets.QLabel(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.bms_v_label.sizePolicy().hasHeightForWidth())
                self.bms_v_label.setSizePolicy(sizePolicy)
                self.bms_v_label.setMinimumSize(QtCore.QSize(0, 0))
                self.bms_v_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setWeight(50)
                self.bms_v_label.setFont(font)
                self.bms_v_label.setStyleSheet("color: rgb(74, 74, 74);")
                self.bms_v_label.setObjectName("bms_v_label")
                self.bottom_statusbar.addWidget(self.bms_v_label)
                self.bms_v = QtWidgets.QLabel(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.bms_v.sizePolicy().hasHeightForWidth())
                self.bms_v.setSizePolicy(sizePolicy)
                self.bms_v.setMinimumSize(QtCore.QSize(0, 0))
                self.bms_v.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setWeight(50)
                self.bms_v.setFont(font)
                self.bms_v.setObjectName("bms_v")
                self.bottom_statusbar.addWidget(self.bms_v)
                spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
                self.bottom_statusbar.addItem(spacerItem7)
                self.bms_status_label = QtWidgets.QLabel(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.bms_status_label.sizePolicy().hasHeightForWidth())
                self.bms_status_label.setSizePolicy(sizePolicy)
                self.bms_status_label.setMinimumSize(QtCore.QSize(0, 0))
                self.bms_status_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                font.setBold(False)
                font.setWeight(50)
                self.bms_status_label.setFont(font)
                self.bms_status_label.setStyleSheet("color: rgb(74, 74, 74);")
                self.bms_status_label.setObjectName("bms_status_label")
                self.bottom_statusbar.addWidget(self.bms_status_label)
                self.serial_button = QtWidgets.QPushButton(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.serial_button.sizePolicy().hasHeightForWidth())
                self.serial_button.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setFamily("Montserrat")
                font.setPointSize(9)
                self.serial_button.setFont(font)
                self.serial_button.setStyleSheet("background-color: rgb(207, 207, 207);\n"
                "border-radius: 15px;\n"
                "padding: 10px;")
                self.serial_button.setObjectName("serial_button")
                self.bottom_statusbar.addWidget(self.serial_button)
                spacerItem8 = QtWidgets.QSpacerItem(13, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
                self.bottom_statusbar.addItem(spacerItem8)
                self.gridLayout_6.addLayout(self.bottom_statusbar, 6, 0, 1, 4)
                MainWindow.setCentralWidget(self.centralwidget)

                self.serial_button.setCheckable(True)
                self.serial_button.clicked.connect(self.change_color)

                self.time_sync.setCheckable(True)
                self.time_sync.clicked.connect(self.time_sync_bms)

                self.canvas_1 = FigureCanvas(plt.Figure())
                self.empty_layout_1.addWidget(self.canvas_1)

                self.canvas_2 = FigureCanvas(plt.Figure())
                self.empty_layout_2.addWidget(self.canvas_2)

                self.ax = self.canvas_1.figure.subplots()

                self.ax = self.canvas_2.figure.subplots()
                
                self.config_port.addItems(self.config['port'])
                self.config_port.setStyleSheet("font: 9pt \"Montserrat\";")

                self.config_brate.addItems(self.config['baud_rate'])
                self.config_brate.setStyleSheet("font: 9pt \"Montserrat\";")

                MainWindow.setWindowIcon(QtGui.QIcon('icon.png'))

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "Vidur"))
                self.time_sync.setText(_translate("MainWindow", "PushButton"))
                self.battery_stats_label.setText(_translate("MainWindow", "BATTERY STATISTICS"))
                self.total_current_label.setText(_translate("MainWindow", "Total Current:"))
                self.soc_label.setText(_translate("MainWindow", "SoC:"))
                self.status.setText(_translate("MainWindow", "Charging"))
                self.soc.setText(_translate("MainWindow", "98%"))
                self.voltage.setText(_translate("MainWindow", "xx V"))
                self.voltage_label.setText(_translate("MainWindow", "Battery Voltage:"))
                self.total_current.setText(_translate("MainWindow", "xx A"))
                self.status_label.setText(_translate("MainWindow", "Status:"))
                self.mosfet_status_label.setText(_translate("MainWindow", "Mosfet Status"))
                self.charging_label.setText(_translate("MainWindow", "Charging:"))
                self.charging.setText(_translate("MainWindow", "Yes"))
                self.discharging_label.setText(_translate("MainWindow", "Disharging:"))
                self.discharging.setText(_translate("MainWindow", "No"))
                self.battery_stats_label_6.setText(_translate("MainWindow", "Temperature (°C)"))
                self.mosfet_temp_label.setText(_translate("MainWindow", "MOSFET:"))
                self.mosfet_temp.setText(_translate("MainWindow", "xxx"))
                self.sensor_2_label.setText(_translate("MainWindow", "Sensor 2:"))
                self.sensor_2.setText(_translate("MainWindow", "xxx"))
                self.sensor_3_label.setText(_translate("MainWindow", "Sensor 3:"))
                self.sensor_3.setText(_translate("MainWindow", "xxx"))
                self.sensor_1_label.setText(_translate("MainWindow", "Sensor 1:"))
                self.sensor_1.setText(_translate("MainWindow", "xxx"))
                self.sensor_4_label.setText(_translate("MainWindow", "Sensor 4:"))
                self.sensor_4.setText(_translate("MainWindow", "xxx"))
                self.chemistry_label.setText(_translate("MainWindow", "Chemistry:"))
                self.chemistry.setText(_translate("MainWindow", "NMC"))
                self.cells_label.setText(_translate("MainWindow", "No. of Cells:"))
                self.cells.setText(_translate("MainWindow", "16"))
                self.design_capacity_label.setText(_translate("MainWindow", "Battery Design Capacity:"))
                self.design_capacity.setText(_translate("MainWindow", "40 Ah"))
                self.battery_min_v_label.setText(_translate("MainWindow", "Minimum Voltage:"))
                self.battery_min_v.setText(_translate("MainWindow", "48 V"))
                self.nominal_v_label.setText(_translate("MainWindow", "Nominal Voltage:"))
                self.nominal_v.setText(_translate("MainWindow", "57.6 V"))
                self.battery_max_v_label.setText(_translate("MainWindow", "Maximum Voltage:"))
                self.battery_max_v.setText(_translate("MainWindow", "67.2 V"))
                self.battery_stats_label_2.setText(_translate("MainWindow", "Cell Statistics"))
                self.max_v_label.setText(_translate("MainWindow", "Maximum Voltage:"))
                self.max_v.setText(_translate("MainWindow", "xx V"))
                self.min_v_label.setText(_translate("MainWindow", "Minimum Voltage"))
                self.min_v.setText(_translate("MainWindow", "xx V"))
                self.avg_cell_v_label.setText(_translate("MainWindow", "Average Cell Voltage:"))
                self.avg_cell_v.setText(_translate("MainWindow", "xx V"))
                self.difference_label.setText(_translate("MainWindow", "Defference:"))
                self.difference.setText(_translate("MainWindow", "xx V"))
                self.battery_stats_label_8.setText(_translate("MainWindow", "Cell Voltage"))
                
                for i in range(test):
                        self.cell_v_label[i].setText(_translate("MainWindow", f"Cell {i+1}:"))
                        self.cell_v[i].setText(_translate("MainWindow", "xxxx mV"))
                
                self.alarm_label.setText(_translate("MainWindow", "Alarm"))
                self.ssc_label.setText(_translate("MainWindow", "Short Circuit"))
                self.over_temp_label.setText(_translate("MainWindow", "Over Temperature"))
                self.over_v_label.setText(_translate("MainWindow", "Over Voltage"))
                self.under_v_label.setText(_translate("MainWindow", "Under Voltage"))
                self.over_c_label.setText(_translate("MainWindow", "Over Current"))
                self.gui_v_label.setText(_translate("MainWindow", "GUI Version:"))
                self.gui_v.setText(_translate("MainWindow", "8239578"))
                self.hardware_v_label.setText(_translate("MainWindow", "Hardware Version:"))
                self.hardware_v.setText(_translate("MainWindow", "124212"))
                self.firmware_v_label.setText(_translate("MainWindow", "Firmware Version:"))
                self.firmware_v.setText(_translate("MainWindow", "124212"))
                self.bms_v_label.setText(_translate("MainWindow", "BMS Serial Version:"))
                self.bms_v.setText(_translate("MainWindow", "124212"))
                self.bms_status_label.setText(_translate("MainWindow", "BMS Status:"))
                self.serial_button.setText(_translate("MainWindow", "Disconnected"))

                date = datetime.now()
                date = date.strftime("%d-%m-%Y")
                self.time_sync.setText(_translate("MainWindow", f"{date}"))

        def check_serial_event(self):
                self.timeout += 1

                serial_thread = threading.Timer(1, self.check_serial_event)

                if ser.is_open == True:
                        serial_thread.start()
                        
                        if ser.in_waiting:                        
                                while True:
                                        try:
                                                line = ser.readline().decode("ascii")
                                                if line[0] != '#':
                                                        break
                                                line = line.lstrip('#')
                                                line = line.rstrip()
                                                line = line.split(',')
                                                line = [int(l) for l in line]
                                                if len(line) != 25:
                                                        break
                                        except:
                                                break

                                        cell_v = line[0:16]

                                        if int(line[23])>25:
                                                self.status.setText("Charging")
                                        elif int(line[23])<-25:
                                                self.status.setText("Discharging")
                                        else:
                                                self.status.setText("Idle")
                                        
                                        self.soc.setText(f"{line[24]} %")
                                        self.voltage.setText(f"{line[20]/100} V")
                                        self.total_current.setText(f"{line[23]} mA")
                                        
                                        if int(line[23])>25:
                                                self.charging.setText("Yes")
                                                self.discharging.setText("No")
                                        elif int(line[23])<-25:
                                                self.charging.setText("No")
                                                self.discharging.setText("Yes")
                                        else:
                                                self.charging.setText("No")
                                                self.discharging.setText("No")
                                        
                                        self.mosfet_temp.setText(f"{line[19]} °C")
                                        self.sensor_1.setText(f"{line[16]} °C")
                                        self.sensor_2.setText(f"{line[17]} °C")
                                        self.sensor_3.setText(f"{line[18]} °C")
                                        self.sensor_4.setText(f"{line[19]} °C")

                                        self.max_v.setText(f"{max(cell_v)} mV")
                                        self.min_v.setText(f"{min(cell_v)} mV")
                                        self.avg_cell_v.setText(f"{int(sum(cell_v)/16)} mV")
                                        self.difference.setText(f"{max(cell_v)-min(cell_v)} mV")

                                        for i in range(len(self.cell_v)):
                                                self.cell_v[i].setText(f"{cell_v[i]} mV")

                                        if len(self.soc_values)<20:
                                                self.soc_values.append(line[24])

                                                self.battery_voltage_values.append((line[20]/100))

                                                time_now = datetime.now()
                                                self.time.append(time_now.strftime("%H:%M:%S"))
                                        else:
                                                self.soc_values.append(line[24])
                                                self.soc_values.pop(0)

                                                self.battery_voltage_values.append((line[20]/100))
                                                self.battery_voltage_values.pop(0)

                                                time_now = datetime.now()
                                                self.time.append(time_now.strftime("%H:%M:%S"))
                                                self.time.pop(0)

                                        self.plot()

                        self.timeout = 0

                if self.timeout >= 1000:
                        self.disconnected()
        
        def connected(self):
                global ser
                ser = serial.Serial(self.config_port.currentText(), baudrate=int(self.config_brate.currentText()), timeout=20)

                if not ser.is_open:
                        ser.open()
                
                self.timeout = 0
                self.check_serial_event()

        def disconnected(self):
                ser_ports = serial.tools.list_ports.comports()
                ports = [port.name for port in ser_ports]
                self.config["port"] = ports
                
                self.config_port.clear()
                self.config_port.addItems(self.config['port'])
                if ser.is_open:
                        ser.close()

        def change_color(self):
                if self.serial_button.isChecked():
                        self.serial_button.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                        "border-radius: 15px;\n"
                        "padding: 10px;")
                        self.serial_button.setText("Connected")
                        try:
                                self.connected()
                        except:
                                pass
                else:
                        self.serial_button.setStyleSheet("background-color: rgb(207, 207, 207);\n"
                        "border-radius: 15px;\n"
                        "padding: 10px;")
                        self.serial_button.setText("Disconnected")
                        try:
                                self.disconnected()
                        except:
                                pass

        def plot(self):
                self.canvas_1.figure.clear()
                ax_1 = self.canvas_1.figure.add_subplot(111)
                ax_1.plot(self.time, self.soc_values, '.-')
                self.canvas_1.figure.autofmt_xdate()
                ax_1.grid()
                ax_1.set_title('SoC vs Time')
                ax_1.set_ylabel('Soc (%)')
                self.canvas_1.draw()

                self.canvas_2.figure.clear()
                ax_2 = self.canvas_2.figure.add_subplot(111)
                ax_2.plot(self.time, self.battery_voltage_values, '.-')
                self.canvas_2.figure.autofmt_xdate()
                ax_2.grid()
                ax_2.set_title('Voltage vs Time')
                ax_2.set_ylabel('Voltage (V)')
                self.canvas_2.draw()

        def time_sync_bms(self):
                if self.serial_button.isChecked():
                        if ser.is_open:
                                time = datetime.now()
                                time = time.strftime("%Y-%m-%d %H:%M:%S")
                                ser.write(bytes(time, 'utf-8'))
                else:
                        pass
        
def main():
        app = QApplication(sys.argv)
        MainWindow = QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())

if __name__ == "__main__":
    while True:
        main()
